# Generated by Django 3.1.1 on 2020-09-24 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(blank=True, max_length=10, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('live', models.BooleanField(default=False)),
                ('live_at', models.DateTimeField(blank=True, null=True)),
                ('not_live_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_on', models.BooleanField()),
                ('detected_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream')),
            ],
        ),
    ]
