# Generated by Django 3.1.1 on 2020-10-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
